layout_spectrum: 0.599624
color:
  saturation: 0.7003426
  brandStrength: 0.4830827
  lightness: 0.5277173
  rhythmicContrast: 0.5662162
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.05889724
name: Geschenke
