name: Geschenke
favicon: null
layout_spectrum: 0.55611
typography_spectrum: 0.05889724
title: Geschenke
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4830827
  lightness: 0.5277173
  saturation: 0.7003426
  rhythmicContrast: 0.5662162
purpose: []
